#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to run this script, type that shell name before the whole
#       command line, like:
#
#           ksh Gradle
#
#       Busybox and similar reduced shells will NOT work, because this script
#       requires all of these POSIX shell features:
#         * functions;
#         * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
#           «${var#prefix}», «${var%suffix}», and «$( cmd )»;
#         * compound commands having a testable exit status, especially «case»;
#         * various built-in commands including «command», «set», and «ulimit».
#
#   Important for patching:
#
#   (2) This script targets any POSIX shell, so it avoids extensions provided
#       by Bash, Ksh, etc; in particular arrays are avoided.
#
#       The "traditional" practice of packing multiple parameters into a single
#       parameter as a string -- e.g. \"$@\" -- is a well known performance
#       problem and here it is actually deprecated, because the semantics of
#       «$@» are different in different shells. Please use one argument per line
#       instead.
#
#   (3) This script is generated from the Groovy template
#       https://github.com/gradle/gradle/blob/HEAD/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
#       within the Gradle project.
#
#       You can find Gradle at https://github.com/gradle/gradle/.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case $( uname ) in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC3045
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC3045
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # don't mess with options #(
              /?*)  t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
                    [ -e "$t" ] ;;                      #(
              *)    false ;;
            esac
        then
            arg=$( cygpath --path --ignore --mixed "$arg" )
        fi
        # Roll the args list around exactly as many times as the number of
        # args, so each arg winds up back in the position where it started, but
        # possibly modified.
        #
        # NB: a `for` loop captures its iteration list before it begins, so
        # changing the positional parameters here affects neither the number of
        # iterations, nor the values presented in `arg`.
        shift                   # remove old arg
        set -- "$@" "$arg"      # push replacement arg
    done
fi


# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Collect all arguments for the java command:
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS can contain fragments of
#     shell script including quotes and variable substitutions, so put them in
#     double quotes to make sure that they get re-expanded; and
#   * put the final (last) argument in double quotes so that the fact that it
#     may contain spaces will not be lost.
set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
#
# With -n1 it outputs one arg per line, with the quotes and backslashes removed.
#
# In Bash we could simply go:
#
#   readarray ARGS < <( xargs -n1 <<<"$var" ) &&
#   set -- "${ARGS[@]}" "$@"
#
# but POSIX shell has neither arrays nor command substitution, so instead we
# post-process each arg (as a line of input to sed) to backslash-escape any
# character that might be a shell metacharacter, then use eval to reverse
# that process (while maintaining the separation between arguments), and wrap
# the whole thing up as a single "set" statement.
#
# This will of course break if any of these variables contains a newline or
# an unmatched quote.
#

eval "set -- $(
        printf '%s\n' "$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS" |
        xargs -n1 |
        sed ' s~[^-[:alnum:]+,./:=@_]~\\&~g; ' |
        tr '\n' ' '
    )" '"$@"'

##############################################################################
#
#   Manzil CI diagnostics
#
#   The GitHub Actions workflow runs Gradle through `... 2>&1 | tee build.log`.
#   A pipeline's exit status is the status of its last command, so `tee` always
#   succeeds and a broken build reports a green job while no APK is produced.
#   The workflow file cannot be edited from here, so this launcher:
#
#     * captures the full Gradle output while still streaming it live,
#     * preserves the real Gradle exit code,
#     * re-emits compiler diagnostics as GitHub Actions annotations
#       (`::error::` workflow commands) so a failing build is visible through
#       the check-runs API instead of only in the (log-blob) step output,
#     * reports the APK that was produced on success.
#
##############################################################################

MANZIL_TMP="${TMPDIR:-/tmp}"
MANZIL_LOG="$MANZIL_TMP/manzil-gradle-$$.log"
MANZIL_STATUS="$MANZIL_TMP/manzil-gradle-$$.status"

manzil_encode() {
    # Encode stdin as a single GitHub workflow-command data string.
    awk '{ gsub(/%/, "%25"); gsub(/\r/, ""); printf "%s%%0A", $0 }' | cut -c1-4000
}

manzil_emit_chunks() {
    # $1 = annotation level, $2 = tag, $3 = max chunks, stdin = text to publish
    # in ~1.5 KB chunks.
    level="$1"
    tag="$2"
    max_chunks="$3"
    chunk="$MANZIL_TMP/manzil-chunk-$$.txt"
    rm -f "$chunk".*
    sed -e '/^[[:space:]]*$/d' > "$chunk"
    split -b 1500 "$chunk" "$chunk." 2>/dev/null || cp "$chunk" "$chunk.aa"
    count=0
    for part in "$chunk".*; do
        [ -f "$part" ] || continue
        count=$((count + 1))
        [ "$count" -gt "$max_chunks" ] && break
        printf '::%s::[manzil %s %d] %s\n' "$level" "$tag" "$count" "$(manzil_encode < "$part")"
    done
    rm -f "$chunk".*
}

rm -f "$MANZIL_LOG" "$MANZIL_STATUS"
{ "$JAVACMD" "$@" 2>&1; echo $? > "$MANZIL_STATUS"; } | tee "$MANZIL_LOG"
MANZIL_EXIT=$(cat "$MANZIL_STATUS" 2>/dev/null)
[ -n "$MANZIL_EXIT" ] || MANZIL_EXIT=1

if [ "$MANZIL_EXIT" -ne 0 ]; then
    echo ""
    echo "===== Manzil CI diagnostics: Gradle exited with $MANZIL_EXIT ====="
    # Failure summary first: it says which task blew up and why.
    {
        grep -hE '^FAILURE|^What went wrong|^\* (What|Where|Try)|^Caused by:|Execution failed for task|^> Task .* FAILED|BUILD FAILED|^> ' "$MANZIL_LOG" 2>/dev/null |
            grep -vE '^[[:space:]]*(at |\.\.\. [0-9]+ more)' | head -80
        echo "--- last 40 lines of Gradle output (stack frames removed) ---"
        grep -vE '^[[:space:]]*(at |\.\.\. [0-9]+ more)' "$MANZIL_LOG" 2>/dev/null | tail -n 40
    } | manzil_emit_chunks error summary 5
    # Then every compiler / lint diagnostic we can find.
    {
        grep -hE '^e: |error:|^w: .*(error|cannot)|Lint error|unresolved reference|Compilation error|^manzil-failure |\.kts?:[0-9]+:[0-9]+:' "$MANZIL_LOG" 2>/dev/null | head -400
    } | manzil_emit_chunks error diagnostics 20
fi

for apk in app/build/outputs/apk/*/*.apk; do
    if [ -f "$apk" ]; then
        printf '::notice::Manzil APK built: %s (%s bytes)\n' "$apk" "$(wc -c < "$apk" | tr -d ' ')"
    fi
done

rm -f "$MANZIL_LOG" "$MANZIL_STATUS"
exit "$MANZIL_EXIT"
